version: '3.4'

services:
  web:
    build: .
    volumes:
      - ./app:/app  # Bind the app directory for live code changes
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/projectDb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

volumes:
  mongodata:
